### PR TITLE
Add tests workflow

### LINKED ISSUE #2: Tests
There should be units tests.
Please assign me I can do this.

### PR DESCRIPTION
**Pull request by GrognakHouses**
Closes #2 

Add good tests to test pack integrity of the blockchain.

Blockchain because Minecraft block.

### CODE REVIEW

**Comment by GrognakHouses** [comment]
LGTM!

**Comment by GrognakHouses** [comment]
Looks good

**Comment by GrognakHouses** [comment]
to me!

**Comment by supercam19** [comment]
ok since you said it looks good i will add it 👍🏻

**Pull request merged**
